### PR TITLE
fixed token expiration time stamp

### PR DESCRIPTION
**Pull request by dipta007**
Found a bug in token expiration time stamp.
Issue is addressed [here](https://github.com/docusign/eg-01-node-jwt/issues/6).

### CODE REVIEW

**Comment by LarryKlugerDS** [comment]
Hi,
Thank you for spotting the issue. In fact there are several issues, if you could update your pull request, that would be great!

The reason for the `tokeReplaceMin` is that we don't want to come down to the millisecond in terms of re-using the existing token. Instead, `tokeReplaceMin` serves as a 10 minute buffer--if the token is going to expire within the next 10 minutes, then replace it.

But there are two bugs with the existing code--the moment#add mutates the variable, so 10 minutes is being added each time. Plus (I think!) the comparison is wrong--instead of adding 10 minutes and then seeing if the new expiration time is before the current time, 10 minutes should be subtracted! (Eg expiration is 5pm. Current time is 4:55pm. 5pm - 10 min is before 4:55 so a new token is needed.)

To fix:
Update line 97
from
````
  const expiresAt = moment().add(results.body.expires_in, 's');
to
  const expiresAt = moment().add(results.body.expires_in, 's').subtract(tokenReplaceMin, 'm');
````
Combine that with your current change and that should solve it.

Please let me know your comments/thoughts.

Thank you,
Larry

**Comment by dipta007** [comment]
> Hi,
> Thank you for spotting the issue. In fact there are several issues, if you could update your pull request, that would be great!
> 
> The reason for the `tokeReplaceMin` is that we don't want to come down to the millisecond in terms of re-using the existing token. Instead, `tokeReplaceMin` serves as a 10 minute buffer--if the token is going to expire within the next 10 minutes, then replace it.
> 
> But there are two bugs with the existing code--the moment#add mutates the variable, so 10 minutes is being added each time. Plus (I think!) the comparison is wrong--instead of adding 10 minutes and then seeing if the new expiration time is before the current time, 10 minutes should be subtracted! (Eg expiration is 5pm. Current time is 4:55pm. 5pm - 10 min is before 4:55 so a new token is needed.)
> 
> To fix:
> Update line 97
> from
> 
> ```
>   const expiresAt = moment().add(results.body.expires_in, 's');
> to
>   const expiresAt = moment().add(results.body.expires_in, 's').subtract(tokenReplaceMin, 'm');
> ```
> 
> Combine that with your current change and that should solve it.
> 
> Please let me know your comments/thoughts.
> 
> Thank you,
> Larry

yes I also think so, I will update the PR
Thanks

**Comment by dipta007** [comment]
I think with the last commit, its perfect now @LarryKlugerDS

**Comment by khamasaki** [comment]
Hi - just wanted to note that I ran into this as well, and that this PR should really be merged to prevent others from having the same problem. As the code is written, it will attempt to use expired tokens for 10 minutes each time, which is not good.

**Comment by LarryKlugerDS** [comment]
Thank you. We've had a change of engineers for the code examples. I will re-raise this with the new team. Regards, Larry

**Comment by khamasaki** [comment]
Thank you!

**Pull request merged**
